version: "3"

tasks:
    build:
        cmds:
            - task: build-cmd
            - task: build-daemon
            - task: build-apt-server

    build-daemon:
        cmds:
            - go build -o catalogue-daemon ./cmd/daemon
    build-cmd:
        cmds:
            - go build -o catalogue ./cmd/catalogue

    build-apt-server:
        cmds:
            - go build -o catalogue-apt-server ./cmd/apt-catalogue-server
