version: "3"

tasks:
    compile:
        cmds:
            - task: compile-cmd
            - task: compile-daemon
            - task: compile-apt-server

    compile-daemon:
        cmds:
            - go build -o ./build/daemon ./cmd/daemon
    compile-cmd:
        cmds:
            - go build -o ./build/catalogue ./cmd/catalogue

    compile-apt-server:
        cmds:
            - go build -o ./build/apt-server ./cmd/apt-catalogue-server

    clean:
        cmds:
            - rm -rf ./build

    build:
        requires:
            vars: [VERSION]
        cmds:
            - rm -rf ./build
            - echo -n "{{.VERSION}}" > ./cmd/catalogue/version.txt
            - mkdir -p build
            - sed 's/__VERSION__/{{.VERSION}}/g' control-template.txt > ./build/control.txt
            - task: compile
            - install -D ./build/control.txt ./build/deb/control/control
            - install -D ./build/apt-server ./build/deb/data/usr/bin/catalogue-apt-server
            - install -D ./build/catalogue ./build/deb/data/usr/bin/catalogue
            - install -D ./apt-server.service ./build/deb/data/lib/systemd/system/catalogue-apt-server.service
            - ./build/catalogue deb --in ./build/deb --out ./build/catalogue.deb
